<CameraScreen>:
   GridLayout:
      cols: 1 
      Camera: 
         id: camera
         resolution: (648, 480)
         play: False
      Button: 
         text: 'Start Camera' if root.ids.camera.play == False else 'Stop Camera'
         on_press: root.start() if root.ids.camera.play == False else root.stop()
      Button: 
         text: 'Capture'

<RootWidget>:
   CameraScreen:
      id: camera_screen
      name: 'camera_screen'