<FirstScreen>:
   GridLayout:
      cols: 1
      padding: 10
      spacing: 5
      Image:
         id: img
         size_hint_y: 0.82
      TextInput:
         id: prompt
         size_hint_y: 0.08
         font_size: 12
      Button:
         text: 'Search Image'
         size_hint_y: 0.1
         on_press: root.search_image()

<RootWidget>:
   FirstScreen:
      id: first_screen
      name: 'first_screen'